/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as MyLessonsRouteImport } from './routes/my-lessons'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PayRouteImport } from './routes/pay'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as InstructorsIndexRouteImport } from './routes/instructors.index'
import { Route as InstructorsSlugRouteImport } from './routes/instructors.$slug'
import { Route as ResultsTokenRouteImport } from './routes/results.$token'
import { Route as TestTokenRouteImport } from './routes/test.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLessonsRoute = MyLessonsRouteImport.update({
  id: '/my-lessons',
  path: '/my-lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const InstructorsIndexRoute = InstructorsIndexRouteImport.update({
  id: '/instructors/',
  path: '/instructors/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsSlugRoute = InstructorsSlugRouteImport.update({
  id: '/instructors/$slug',
  path: '/instructors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsTokenRoute = ResultsTokenRouteImport.update({
  id: '/results/$token',
  path: '/results/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTokenRoute = TestTokenRouteImport.update({
  id: '/test/$token',
  path: '/test/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/guide': typeof GuideRoute
  '/my-lessons': typeof MyLessonsRoute
  '/packages': typeof PackagesRoute
  '/pay': typeof PayRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tips': typeof TipsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/instructors/$slug': typeof InstructorsSlugRoute
  '/results/$token': typeof ResultsTokenRoute
  '/test/$token': typeof TestTokenRoute
  '/instructors/': typeof InstructorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/guide': typeof GuideRoute
  '/my-lessons': typeof MyLessonsRoute
  '/packages': typeof PackagesRoute
  '/pay': typeof PayRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tips': typeof TipsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/instructors/$slug': typeof InstructorsSlugRoute
  '/results/$token': typeof ResultsTokenRoute
  '/test/$token': typeof TestTokenRoute
  '/instructors': typeof InstructorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/guide': typeof GuideRoute
  '/my-lessons': typeof MyLessonsRoute
  '/packages': typeof PackagesRoute
  '/pay': typeof PayRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tips': typeof TipsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/instructors/$slug': typeof InstructorsSlugRoute
  '/results/$token': typeof ResultsTokenRoute
  '/test/$token': typeof TestTokenRoute
  '/instructors/': typeof InstructorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/guide'
    | '/my-lessons'
    | '/packages'
    | '/pay'
    | '/sitemap.xml'
    | '/tips'
    | '/admin/reset-password'
    | '/instructors/$slug'
    | '/results/$token'
    | '/test/$token'
    | '/instructors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/guide'
    | '/my-lessons'
    | '/packages'
    | '/pay'
    | '/sitemap.xml'
    | '/tips'
    | '/admin/reset-password'
    | '/instructors/$slug'
    | '/results/$token'
    | '/test/$token'
    | '/instructors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/guide'
    | '/my-lessons'
    | '/packages'
    | '/pay'
    | '/sitemap.xml'
    | '/tips'
    | '/admin/reset-password'
    | '/instructors/$slug'
    | '/results/$token'
    | '/test/$token'
    | '/instructors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  GuideRoute: typeof GuideRoute
  MyLessonsRoute: typeof MyLessonsRoute
  PackagesRoute: typeof PackagesRoute
  PayRoute: typeof PayRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TipsRoute: typeof TipsRoute
  InstructorsSlugRoute: typeof InstructorsSlugRoute
  ResultsTokenRoute: typeof ResultsTokenRoute
  TestTokenRoute: typeof TestTokenRoute
  InstructorsIndexRoute: typeof InstructorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-lessons': {
      id: '/my-lessons'
      path: '/my-lessons'
      fullPath: '/my-lessons'
      preLoaderRoute: typeof MyLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/instructors/': {
      id: '/instructors/'
      path: '/instructors'
      fullPath: '/instructors/'
      preLoaderRoute: typeof InstructorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors/$slug': {
      id: '/instructors/$slug'
      path: '/instructors/$slug'
      fullPath: '/instructors/$slug'
      preLoaderRoute: typeof InstructorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$token': {
      id: '/results/$token'
      path: '/results/$token'
      fullPath: '/results/$token'
      preLoaderRoute: typeof ResultsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$token': {
      id: '/test/$token'
      path: '/test/$token'
      fullPath: '/test/$token'
      preLoaderRoute: typeof TestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminResetPasswordRoute: AdminResetPasswordRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  GuideRoute: GuideRoute,
  MyLessonsRoute: MyLessonsRoute,
  PackagesRoute: PackagesRoute,
  PayRoute: PayRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TipsRoute: TipsRoute,
  InstructorsSlugRoute: InstructorsSlugRoute,
  ResultsTokenRoute: ResultsTokenRoute,
  TestTokenRoute: TestTokenRoute,
  InstructorsIndexRoute: InstructorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
